-- TradeLinkPro initial schema
-- Paste this into Supabase Dashboard → SQL Editor → New query → Run.

-- ============================================================
-- TABLES
-- ============================================================

create table if not exists contractors (
  id            bigint generated by default as identity primary key,
  name          text not null,
  trade         text not null,
  location      text not null,
  rating        numeric(2,1) default 0,
  reviews_count int default 0,
  hourly        int,
  available     boolean default true,
  tags          text[] default '{}',
  bio           text,
  avatar        text,
  created_at    timestamptz default now()
);

create table if not exists jobs (
  id          bigint generated by default as identity primary key,
  title       text not null,
  trade       text not null,
  location    text not null,
  budget      numeric,
  description text,
  posted_by   uuid references auth.users(id) on delete set null,
  created_at  timestamptz default now()
);

create table if not exists reviews (
  id            bigint generated by default as identity primary key,
  contractor_id bigint references contractors(id) on delete cascade not null,
  author        text not null,
  stars         int check (stars between 1 and 5) not null,
  text          text not null,
  created_at    timestamptz default now()
);

create table if not exists messages (
  id            bigint generated by default as identity primary key,
  contractor_id bigint references contractors(id) on delete cascade not null,
  sender        text check (sender in ('me','them')) not null,
  text          text not null,
  created_at    timestamptz default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- RLS is on by default (you enabled it at project creation).
-- These policies allow public read + public insert so the MVP
-- works without auth. TIGHTEN BEFORE LAUNCH.
-- ============================================================

alter table contractors enable row level security;
alter table jobs        enable row level security;
alter table reviews     enable row level security;
alter table messages    enable row level security;

create policy "public read contractors"  on contractors for select using (true);
create policy "public read jobs"         on jobs        for select using (true);
create policy "public read reviews"      on reviews     for select using (true);
create policy "public read messages"     on messages    for select using (true);

create policy "public insert jobs"       on jobs        for insert with check (true);
create policy "public insert reviews"    on reviews     for insert with check (true);
create policy "public insert messages"   on messages    for insert with check (true);

-- ============================================================
-- DATA API GRANTS
-- Required because "Automatically expose new tables" was disabled
-- at project creation. PostgREST checks GRANTs before RLS.
-- ============================================================

grant usage on schema public to anon, authenticated;
grant select on contractors, reviews, messages, jobs to anon, authenticated;
grant insert on jobs, reviews, messages              to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ============================================================
-- SEED DATA (mirrors the hardcoded list in src/App.jsx)
-- ============================================================

insert into contractors (name, trade, location, rating, reviews_count, hourly, available, tags, bio, avatar) values
  ('Iron Ridge Builders', 'General Contractor', 'Austin, TX',   4.9, 47, 95, true,  '{Renovations,New Builds,Framing}',     '15 years of residential and commercial builds. Licensed & insured.', 'IR'),
  ('BlueSky Plumbing',    'Plumber',            'Denver, CO',   4.7, 83, 80, true,  '{Pipes,Water Heaters,Drain Repair}',    'Fast, reliable plumbing for residential and light commercial jobs.', 'BS'),
  ('Volt Pro Electric',   'Electrician',        'Phoenix, AZ',  4.8, 62, 90, false, '{Panel Upgrades,Wiring,EV Chargers}',   'Certified master electrician. All permits handled.',                  'VP'),
  ('Apex Roofing Co.',    'Roofer',             'Dallas, TX',   4.6, 34, 75, true,  '{Shingles,Flat Roof,Gutters}',          'Storm damage? We had you covered — literally.',                       'AR'),
  ('CleanCut Carpentry',  'Carpenter',          'Nashville, TN',5.0, 21, 70, true,  '{Cabinets,Trim,Decks}',                 'Precision woodworking for custom homes and renovations.',             'CC'),
  ('TileKing Masonry',    'Mason',              'Chicago, IL',  4.5, 58, 85, false, '{Tile,Concrete,Brick}',                 'Commercial and residential masonry with 20+ years experience.',       'TK');

insert into reviews (contractor_id, author, stars, text) values
  (1, 'Sunrise Homes LLC',  5, 'Iron Ridge did an incredible job on our 12-unit build. On time, on budget.'),
  (1, 'The Patel Family',   5, 'Remodeled our entire ground floor. Couldn''t be happier!'),
  (2, 'GreenLeaf Properties', 4, 'Fast response and clean work. Minor scheduling hiccup but resolved quickly.');

insert into messages (contractor_id, sender, text) values
  (1, 'them', 'Hi! I saw your job posting for the kitchen remodel. I''d love to discuss.');
