-- Migration 013: job releases (with reasons) + support tickets
-- Paste into Supabase Dashboard → SQL Editor → New query → Run.

-- ============================================================
-- JOB RELEASES
-- When a customer boots a contractor off their accepted job. Keeps a
-- history so admins can see patterns per contractor (ghosting, etc.).
-- ============================================================

create table if not exists job_releases (
  id                bigint generated by default as identity primary key,
  job_id            bigint references jobs(id)          on delete cascade not null,
  contractor_row_id bigint references contractors(id)   on delete set null,
  contractor_user_id uuid  references auth.users(id)    on delete set null,
  released_by       uuid   references auth.users(id)    on delete set null not null,
  reason            text   not null,
  notes             text,
  created_at        timestamptz default now()
);

create index if not exists job_releases_contractor_idx on job_releases (contractor_row_id, created_at desc);

alter table job_releases enable row level security;

drop policy if exists "customers insert own releases"       on job_releases;
drop policy if exists "customer sees own; admin sees all"   on job_releases;

create policy "customers insert own releases" on job_releases
  for insert with check (
    released_by = auth.uid()
    and exists (select 1 from jobs j where j.id = job_id and j.posted_by = auth.uid())
  );

create policy "customer sees own; admin sees all" on job_releases
  for select using (
    released_by = auth.uid() or is_admin(auth.uid())
  );

grant select, insert on job_releases to authenticated;
grant select on job_releases to service_role;

-- ============================================================
-- SUPPORT TICKETS
-- Any signed-in user can submit; email captured for reply-to.
-- Admins see everything and can mark them resolved.
-- ============================================================

create table if not exists support_tickets (
  id           bigint generated by default as identity primary key,
  user_id      uuid references auth.users(id) on delete set null,
  email        text not null,
  subject      text not null,
  body         text not null,
  status       text default 'open' check (status in ('open','closed')),
  created_at   timestamptz default now(),
  resolved_at  timestamptz,
  resolved_by  uuid references auth.users(id) on delete set null
);

alter table support_tickets enable row level security;

drop policy if exists "anyone can submit tickets"                       on support_tickets;
drop policy if exists "user sees own tickets or admin sees all"         on support_tickets;
drop policy if exists "admins update tickets"                           on support_tickets;

create policy "anyone can submit tickets" on support_tickets
  for insert with check (true);

create policy "user sees own tickets or admin sees all" on support_tickets
  for select using (
    (user_id is not null and user_id = auth.uid())
    or is_admin(auth.uid())
  );

create policy "admins update tickets" on support_tickets
  for update using (is_admin(auth.uid())) with check (is_admin(auth.uid()));

grant insert on support_tickets to anon, authenticated;
grant select on support_tickets to authenticated;
grant select, insert, update on support_tickets to service_role;
